name: base_ui
description: base_ui用Flutterパッケージ
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.9.0
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  flutter_localizations:
    sdk: flutter
  gap: ^3.0.1
  intl: any # flutter_localizations に固定されたバージョンを利用する
  path: ^1.9.1
  path_provider: ^2.1.5
  pdfrx: ^2.1.3

dev_dependencies:
  altive_lints: ^1.22.0
  arb_translate:
    # パッケージが動作しないので、以下のフォーク先を利用する：
    # https://github.com/leancodepl/arb_translate/pull/24
    git:
      url: https://github.com/flowhorn/arb_translate.git
  build_runner: ^2.4.15
  custom_lint: ^0.7.6
  flutter_gen_runner: ^5.10.0
  flutter_test:
    sdk: flutter
  grinder: ^0.9.5
  mockito: ^5.4.6

flutter:
  # `flutter gen-l10n` による翻訳文字列生成を有効化する。
  # https://docs.flutter.dev/release/breaking-changes/flutter-generate-i10n-source
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/pdfs/
    - assets/sounds/
